# roles/spark-master/tasks/check.yml
---
- name: check | port
  wait_for:
    port: "{{ spark_master_port | default(7077) }}"
    host: "{{ ansible_default_ipv4['address'] }}"
    delay: 1
  when: "cluster_interface is not defined"

- name: check | port
  wait_for:
    port: "{{ spark_master_port | default(7077) }}"
    host: "{{ hostvars[inventory_hostname]['ansible_'+cluster_interface]['ipv4']['address'] }}"
    delay: 1
  when: "cluster_interface is defined"
